In [80]:
import torch
import torch.cuda
print(torch.__version__)
print(torch.cuda)

2.6.0
<module 'torch.cuda' from '/opt/conda/lib/python3.12/site-packages/torch/cuda/__init__.py'>


In [26]:
# Scalar
scalar = torch.tensor(7)
print("Scaler : ", scalar)
print("Scaler dtype : ", scalar.dtype)
print("Scaler shape : ", scalar.shape)
print("Scaler ndim : ", scalar.ndim)
print("Scaler item() : ", scalar.item())
print("Scaler item : ", scalar.item)

Scaler :  tensor(7)
Scaler dtype :  torch.int64
Scaler shape :  torch.Size([])
Scaler ndim :  0
Scaler item() :  7
Scaler item :  <built-in method item of Tensor object at 0x7f0f02188910>


In [27]:
# Vector
vector = torch.tensor([7, 7])
print("Vector : ", vector)
print("Vector dtype : ", vector.dtype)
print("Vector shape : ", vector.shape)
print("Vector ndim : ", vector.ndim)
#print(vector.item())
print("Vector item : ", vector.item)

Vector :  tensor([7, 7])
Vector dtype :  torch.int64
Vector shape :  torch.Size([2])
Vector ndim :  1
Vector item :  <built-in method item of Tensor object at 0x7f0f0218afd0>


In [29]:
# Matrix
Matrix = torch.tensor([[11, 22],
                       [33, 44]])

print("Maxtrix : ", Matrix)
print("Maxtrix dtype : ", Matrix.dtype)
print("Maxtrix shape : ", Matrix.shape)
print("Maxtrix ndim : ", Matrix.ndim)
#print(vector.item())
print("Maxtrix item : ", Matrix.item)

Maxtrix :  tensor([[11, 22],
        [33, 44]])
Maxtrix dtype :  torch.int64
Maxtrix shape :  torch.Size([2, 2])
Maxtrix ndim :  2
Maxtrix item :  <built-in method item of Tensor object at 0x7f0f0218be80>


In [52]:
# Tensor
Tensor = torch.tensor([[[11]],[[11]],[[11]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11]],

        [[11]],

        [[11]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([3, 1, 1])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f015580f0>


In [53]:
# Tensor
Tensor = torch.tensor([[[11, 22, 33]],[[11, 44, 55]],[[11, 66, 77]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22, 33]],

        [[11, 44, 55]],

        [[11, 66, 77]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([3, 1, 3])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f00ae8aa0>


In [46]:
# Tensor
Tensor = torch.tensor([[[11],
                        [44]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11],
         [44]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 2, 1])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f049c33e0>


In [44]:
# Tensor
Tensor = torch.tensor([[[11, 22],
                        [44, 55]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22],
         [44, 55]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 2, 2])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f021ef9d0>


In [45]:
# Tensor
Tensor = torch.tensor([[[11, 22, 33],
                        [44, 55, 66]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22, 33],
         [44, 55, 66]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 2, 3])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f01664870>


In [43]:
# Tensor
Tensor = torch.tensor([[[11, 22],
                        [44, 55],
                        [77, 88]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22],
         [44, 55],
         [77, 88]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 3, 2])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f01665a40>


In [39]:
# Tensor
Tensor = torch.tensor([[[11, 22, 33],
                        [44, 55, 66],
                        [77, 88, 99]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 3, 3])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f0151a5d0>


In [40]:
# Tensor
Tensor = torch.tensor([[[11, 22, 33, 33],
                        [44, 55, 66, 66],
                        [77, 88, 99, 99]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22, 33, 33],
         [44, 55, 66, 66],
         [77, 88, 99, 99]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 3, 4])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f0107a490>


In [41]:
# Tensor
Tensor = torch.tensor([[[11, 22, 33],
                        [44, 55, 66],
                        [77, 88, 99]],
                       [[11, 22, 33],
                        [44, 55, 66],
                        [77, 88, 99]],
                       [[11, 22, 33],
                        [44, 55, 66],
                        [77, 88, 99]]
                      ])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]],

        [[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]],

        [[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([3, 3, 3])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f01519d60>


In [57]:
# Creating a random tensor of size (3, 5)

random_tensor = torch.rand(size=(3,5))
random_tensor, random_tensor.dtype

(tensor([[0.2466, 0.1682, 0.5398, 0.6219, 0.1169],
         [0.2634, 0.2542, 0.3266, 0.7572, 0.6155],
         [0.8388, 0.8437, 0.4867, 0.2450, 0.7942]]),
 torch.float32)

In [58]:
# Creating a random tensor of size (1, 3, 5)

random_tensor = torch.rand(size=(1,3,5))
random_tensor, random_tensor.dtype

(tensor([[[0.0716, 0.1062, 0.7012, 0.9779, 0.2481],
          [0.3246, 0.5691, 0.6871, 0.9642, 0.3162],
          [0.8967, 0.9648, 0.1587, 0.7738, 0.2198]]]),
 torch.float32)

In [60]:
# Creating a random tensor of size (2, 3, 5)

random_tensor = torch.rand(size=(0,3,5))
random_tensor, random_tensor.dtype

(tensor([], size=(0, 3, 5)), torch.float32)

In [63]:
# Creating a random tensor of size (2, 3, 5)

random_tensor = torch.rand(size=(1,3,1))
random_tensor, random_tensor.dtype

(tensor([[[0.9527],
          [0.6970],
          [0.6318]]]),
 torch.float32)

In [65]:
# Creating a random tensor of size (100, 256, 256)

random_tensor = torch.rand(size=(100, 256, 256))
random_tensor, random_tensor.dtype, random_tensor.ndim, random_tensor.shape

(tensor([[[0.8746, 0.6853, 0.5973,  ..., 0.2140, 0.6113, 0.0998],
          [0.5550, 0.9934, 0.8809,  ..., 0.0786, 0.7725, 0.2511],
          [0.6479, 0.0847, 0.4803,  ..., 0.6467, 0.4150, 0.0726],
          ...,
          [0.6834, 0.7084, 0.2208,  ..., 0.7852, 0.7667, 0.9339],
          [0.4169, 0.6736, 0.0692,  ..., 0.7984, 0.3733, 0.1654],
          [0.7373, 0.9991, 0.2231,  ..., 0.4576, 0.7775, 0.2030]],
 
         [[0.4116, 0.3754, 0.3543,  ..., 0.0018, 0.5664, 0.5067],
          [0.3229, 0.5807, 0.7622,  ..., 0.4065, 0.7418, 0.7132],
          [0.7971, 0.7149, 0.1867,  ..., 0.7611, 0.3298, 0.6004],
          ...,
          [0.5675, 0.2209, 0.1485,  ..., 0.3577, 0.7333, 0.7981],
          [0.5375, 0.2823, 0.2605,  ..., 0.1001, 0.0536, 0.9994],
          [0.8164, 0.1031, 0.6864,  ..., 0.2697, 0.1812, 0.4143]],
 
         [[0.9894, 0.7311, 0.9061,  ..., 0.8603, 0.7424, 0.7750],
          [0.3044, 0.6834, 0.6330,  ..., 0.4972, 0.4095, 0.5910],
          [0.9955, 0.9202, 0.7444,  ...,

In [73]:
# Zero Tensors of random size

zero = torch.zeros(size=(2, 3, 4))

zero, zero.dtype, zero.shape, zero.ndim

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 torch.float32,
 torch.Size([2, 3, 4]),
 3)

In [74]:
# One Tensors of random size

Ones = torch.ones(size=(1, 2, 3))

Ones, Ones.dtype, Ones.shape, Ones.ndim

(tensor([[[1., 1., 1.],
          [1., 1., 1.]]]),
 torch.float32,
 torch.Size([1, 2, 3]),
 3)

In [85]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                      dtype = None, 
                      device = None, 
                      requires_grad = False
                     )

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [88]:
# Of datatype float16 - 2 bytes
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [89]:
# Of datatype float16 - 2 bytes
int_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.int16)
int_16_tensor, int_16_tensor.dtype

(tensor([3, 6, 9], dtype=torch.int16), torch.int16)

### Getting information from tensors¶

In [90]:
# Create a tensor
some_tensor = torch.rand(3, 5)

print(some_tensor)
print(f"Shape of Tensor : ", {some_tensor.shape})
print(f"DataType of Tensor : {some_tensor.dtype}")
print(f"Device Tensor is stored on : {some_tensor.device}")


tensor([[0.8440, 0.9148, 0.8675, 0.3463, 0.1739],
        [0.7128, 0.4879, 0.8288, 0.9869, 0.1418],
        [0.3355, 0.1638, 0.6107, 0.1360, 0.4030]])
Shape of Tensor :  {torch.Size([3, 5])}
DataType of Tensor : torch.float32
Device Tensor is stored on : cpu


## Manipulating tensors (tensor operations)

### Basic operations

In [123]:
# Creating a tensor and adding the scalar value to it
tensor = torch.tensor([11, 22, 33])
print( tensor - 3) # tensor does not change value until you assign the video


tensor = tensor + 123
print(tensor.shape)
print(tensor)

tensor = tensor * 10
print(tensor)

tensor([ 8, 19, 30])
torch.Size([3])
tensor([134, 145, 156])
tensor([1340, 1450, 1560])


In [121]:
tensor_2d = torch.tensor([[11, 22, 33]])
tensor_2d = tensor_2d + 123
print(tensor_2d.shape)
print(tensor_2d)

tensor_2d = tensor_2d * 100
print(tensor_2d)

torch.Size([1, 3])
tensor([[134, 145, 156]])
tensor([[13400, 14500, 15600]])


In [119]:
tensor_3d = torch.tensor([[[11, 22, 33]]])
tensor_3d = tensor_3d + 123
print(tensor_3d.shape)
print(tensor_3d)

tensor_3d = tensor_3d * 1000
print(tensor_3d)

torch.Size([1, 1, 3])
tensor([[[134, 145, 156]]])
tensor([[[134000, 145000, 156000]]])


In [141]:
### You can also use torch functions to add or multiply

tensor = torch.randint(low = 0, high = 100, size = (1, 2, 3), dtype=torch.int8)

tensor

tensor([[[87, 75, 97],
         [ 2, 76, 36]]], dtype=torch.int8)

In [142]:
torch.multiply(tensor, 10)

tensor([[[102, -18, -54],
         [ 20,  -8, 104]]], dtype=torch.int8)

In [146]:
tensor = torch.randint(low = 0, high = 100, size = (1, 2, 3), dtype=torch.int8)
torch.multiply(tensor, 10.0)

tensor([[[920., 260., 550.],
         [460., 970., 670.]]])

In [150]:
tensor = torch.rand((2, 3), dtype = torch.float32)
print(tensor, "*", tensor)
print("\nEquals:", tensor * tensor)

tensor([[0.1238, 0.3300, 0.4168],
        [0.9837, 0.9763, 0.7129]]) * tensor([[0.1238, 0.3300, 0.4168],
        [0.9837, 0.9763, 0.7129]])

Equals: tensor([[0.0153, 0.1089, 0.1737],
        [0.9677, 0.9531, 0.5083]])


In [151]:
tensor1 = torch.rand((2, 3), dtype = torch.float32)

tensor2 = torch.rand((2, 3), dtype = torch.float32)

print(tensor1, "*", tensor1)
print("\nEquals:", tensor * tensor)

tensor([[0.9731, 0.0438, 0.1065],
        [0.8375, 0.2640, 0.3101]]) * tensor([[0.9731, 0.0438, 0.1065],
        [0.8375, 0.2640, 0.3101]])

Equals: tensor([[0.0153, 0.1089, 0.1737],
        [0.9677, 0.9531, 0.5083]])


In [164]:
# Element-wise multiplication (“multiply matching cells”)
tensor1 = torch.rand((2, 3), dtype = torch.float32)
print(tensor1.shape, tensor1.ndim)

tensor2 = torch.rand((2, 3), dtype = torch.float32)
print(tensor2.shape, tensor2.ndim)

print("\n", tensor1, "\n*\n", tensor2)
print("\nEquals:", tensor1 * tensor2)

torch.Size([2, 3]) 2
torch.Size([2, 3]) 2

 tensor([[0.8536, 0.7235, 0.0686],
        [0.1087, 0.5727, 0.8601]]) 
*
 tensor([[0.3383, 0.9870, 0.0730],
        [0.6541, 0.8555, 0.9749]])

Equals: tensor([[0.2887, 0.7141, 0.0050],
        [0.0711, 0.4899, 0.8385]])


In [165]:
# Element-wise multiplication (“multiply matching cells”)
tensor1 = torch.rand((2, 3), dtype = torch.float32)
print(tensor1.shape, tensor1.ndim)

tensor2 = torch.rand((3, 2), dtype = torch.float32)
print(tensor2.shape, tensor2.ndim)

print("\n", tensor1, "\n*\n", tensor2)
print("\nEquals:", tensor1 * tensor2)

torch.Size([2, 3]) 2
torch.Size([3, 2]) 2

 tensor([[0.0040, 0.8167, 0.5673],
        [0.4145, 0.8458, 0.3871]]) 
*
 tensor([[0.8781, 0.2998],
        [0.8199, 0.6872],
        [0.3917, 0.4278]])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [167]:
# tensor1 @ tensor2 — Matrix multiplication

tensor1 = torch.rand((2, 3), dtype = torch.float32)
print(tensor1.shape, tensor1.ndim)

tensor2 = torch.rand((3, 2), dtype = torch.float32)
print(tensor2.shape, tensor2.ndim)

print("\n", tensor1, "\n*\n", tensor2)
print("\nEquals:", tensor1 @ tensor2)

torch.Size([2, 3]) 2
torch.Size([3, 2]) 2

 tensor([[0.8925, 0.5338, 0.2382],
        [0.8368, 0.4728, 0.8893]]) 
*
 tensor([[0.7182, 0.3929],
        [0.3817, 0.6475],
        [0.3834, 0.6066]])

Equals: tensor([[0.9361, 0.8408],
        [1.1225, 1.1744]])


In [168]:
# This is dot product of two tensors

tensor1 = torch.rand((2, 3), dtype = torch.float32)
print(tensor1.shape, tensor1.ndim)

tensor2 = torch.rand((3, 2), dtype = torch.float32)
print(tensor2.shape, tensor2.ndim)

print("\n", tensor1, "\n*\n", tensor2)
print("\nEquals:", tensor1 @ tensor2)

torch.Size([2, 3]) 2
torch.Size([3, 2]) 2

 tensor([[0.5589, 0.0424, 0.7157],
        [0.0537, 0.3036, 0.7410]]) 
*
 tensor([[0.3909, 0.8699],
        [0.5732, 0.2289],
        [0.5340, 0.9350]])

Equals: tensor([[0.6250, 1.1650],
        [0.5908, 0.8091]])


In [169]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [171]:
# Element wise matrix multiplication

print(tensor * tensor)

tensor([1, 4, 9])


In [172]:
# Matrix Multiplication
print(torch.matmul(tensor, tensor))

tensor(14)


In [173]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))

True
1
NVIDIA A10G


In [174]:
!nvidia-smi

Thu Jan  8 16:02:33 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.105.08             Driver Version: 580.105.08     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A10G                    On  |   00000000:00:1E.0 Off |                    0 |
|  0%   28C    P8             15W /  300W |       3MiB /  23028MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [176]:
# Matrix Multiplication
print(torch.matmul(tensor, tensor))

tensor(14)


In [179]:
tensor = torch.rand(2, 3).to(device)
result = tensor * tensor
print(tensor.device)
print(result.device)

NameError: name 'device' is not defined

In [180]:
%%time
value = 0

for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 1.53 ms, sys: 0 ns, total: 1.53 ms
Wall time: 1.57 ms


tensor(14)

In [182]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 299 μs, sys: 0 ns, total: 299 μs
Wall time: 256 μs


tensor(14)

### One of the most common errors in deep learning (shape errors)

In [183]:
# Shape need to be in the right way

tensor_A = torch.tensor([[1, 2], 
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
print(tensor_A)
tensor_B = torch.tensor( [[7, 8],
                          [10, 11],
                          [12, 13]], dtype = torch.float32)
print(tensor_B)

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [185]:
# Shape need to be in the right way

tensor_A = torch.tensor([[1, 2], 
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
print(tensor_A)
tensor_B = torch.tensor( [[7, 8],
                          [10, 11],
                          [12, 13]], dtype = torch.float32)
print(tensor_B.T)

torch.matmul(tensor_A, tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10., 12.],
        [ 8., 11., 13.]])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [190]:
# Now the inner dimension of matrix multiplication should match, after transpose it should match
print(f"Orginal Shape of Tensor A: = {tensor_A.shape}, Tensor b : = {tensor_B.shape}\n")
print(f"New Shapes: Tensor A : = { tensor_A.shape} ( same as above ), Tensor B : = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <-- Inner Dimensions are same\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape : {output.shape}")

Orginal Shape of Tensor A: = torch.Size([3, 2]), Tensor b : = torch.Size([3, 2])

New Shapes: Tensor A : = torch.Size([3, 2]) ( same as above ), Tensor B : = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <-- Inner Dimensions are same

Output:

tensor([[ 23.,  32.,  38.],
        [ 53.,  74.,  88.],
        [ 83., 116., 138.]])

Output shape : torch.Size([3, 3])


In [192]:
# torch.mm is a shortcut that I can use
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23.,  32.,  38.],
        [ 53.,  74.,  88.],
        [ 83., 116., 138.]])

In [200]:
torch.manual_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
linear = torch.nn.Linear(in_features = 2, out_features = 32, bias = True, device = device)

x = tensor_A.to(device)
output = linear(x)

print(f"Input shape : {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape : torch.Size([3, 2])

Output:
tensor([[-0.5363, -1.9687, -0.4479,  0.0994, -0.2308,  0.9655, -0.1938, -0.7770,
          0.1493, -0.5719,  0.4294, -0.4023, -0.4441, -1.0111,  0.8356, -1.7396,
         -0.1301,  0.0910, -0.4487,  0.3397, -0.3051,  0.9348,  0.8792,  0.9076,
         -0.0142,  0.7113,  0.9309, -1.9655, -0.4714, -0.0837, -1.2472, -1.3167],
        [-1.6025, -3.5562, -1.4697,  0.5017, -0.7806,  1.4306, -0.5781, -2.2752,
          0.3004, -1.3620,  0.0968, -0.1524, -1.4413, -2.3112,  1.7233, -3.6711,
         -0.3651,  0.1752, -1.9042, -0.1095, -0.4342,  2.2199,  2.6698,  0.6785,
         -0.8086,  0.7557,  2.6256, -3.6038, -0.1158,  0.1215, -2.4963, -3.4212],
        [-2.6688, -5.1438, -2.4915,  0.9040, -1.3304,  1.8956, -0.9625, -3.7735,
          0.4514, -2.1521, -0.2358,  0.0974, -2.4384, -3.6114,  2.6110, -5.6027,
         -0.6000,  0.2594, -3.3596, -0.5587, -0.5632,  3.5050,  4.4604,  0.4494,
         -1.6030,  0.8001,  4.3203, -5.2421,  0.2397,  0.3266, -3

### Finding the min, max, mean, sum, etc (aggregation)

In [208]:
# Create a tensor
x = torch.arange(33, 100, 3.3)

x

tensor([33.0000, 36.3000, 39.6000, 42.9000, 46.2000, 49.5000, 52.8000, 56.1000,
        59.4000, 62.7000, 66.0000, 69.3000, 72.6000, 75.9000, 79.2000, 82.5000,
        85.8000, 89.1000, 92.4000, 95.7000, 99.0000])

In [205]:
print(f"Minimum : {x.min()}")
print(f"Maximum : {x.max()}")
print(f"Mean : {x.type(torch.float32).mean()}")
print(f"Sum : {x.sum()}")

Minimum : 0
Maximum : 99
Mean : 49.5
Sum : 1683


In [229]:
float32_tensor = torch.rand(23)
print(tensor)
print(f"Index where Maximum value occurs : {tensor.argmax()}")
print(f"Index where Maximum value occurs : {tensor.argmin()}")

tensor([0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539, 0.1952, 0.0050, 0.3068,
        0.1165, 0.9103, 0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315,
        0.1587, 0.6542, 0.3278, 0.6532, 0.3958])
Index where Maximum value occurs : 0
Index where Maximum value occurs : 7


In [230]:
tensor.dtype

torch.float32

In [231]:
float16_tensor = torch.rand(23, dtype = torch.float16)
print(tensor_2)

tensor([0.7739, 0.9253, 0.6890, 0.5005, 0.4985, 0.6899, 0.2759, 0.5513, 0.8765,
        0.9009, 0.7324, 0.3428, 0.1958, 0.3560, 0.7710, 0.0786, 0.0981, 0.9673,
        0.4858, 0.1313, 0.9209, 0.3979, 0.6318], dtype=torch.float16)


In [232]:
import random

int8_tensor = torch.rand(23, dtype = torch.float32)*100

int8_tensor = int8_tensor.to(dtype = torch.int8)

print(int8_tensor)

tensor([61, 59, 12,  3, 50, 95, 78, 20, 43, 13, 25, 59, 77, 91,  4, 83, 14, 68,
        92, 50, 95,  7, 30], dtype=torch.int8)


In [235]:
int8_tensor.stride()

(1,)

In [237]:
tensor = torch.rand(2,3)
tensor

tensor([[0.6602, 0.2190, 0.0941],
        [0.5541, 0.6481, 0.2691]])

In [238]:
tensor.stride()

(3, 1)

In [239]:
tensor = torch.rand(2,3,3)
tensor

tensor([[[0.3601, 0.8377, 0.5398],
         [0.5226, 0.3769, 0.0472],
         [0.0299, 0.2610, 0.2458]],

        [[0.6558, 0.3544, 0.3044],
         [0.9767, 0.6742, 0.8565],
         [0.2579, 0.2958, 0.6838]]])

In [242]:
tensor.stride()

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 4)

In [244]:
data = [[0, 1], [2, 3]]
tensor = tensor.new_tensor(data)
tensor

tensor([[0., 1.],
        [2., 3.]])

In [245]:
tensor = torch.rand(2,3,3)
tensor

tensor([[[0.1669, 0.1731, 0.4759],
         [0.3171, 0.1252, 0.7966],
         [0.9021, 0.5811, 0.4129]],

        [[0.0369, 0.3179, 0.6273],
         [0.7358, 0.4368, 0.3023],
         [0.7786, 0.1018, 0.8160]]])

In [ ]:
tensor.shape