In [24]:
import torch
print(torch.__version__)

2.6.0


In [26]:
# Scalar
scalar = torch.tensor(7)
print("Scaler : ", scalar)
print("Scaler dtype : ", scalar.dtype)
print("Scaler shape : ", scalar.shape)
print("Scaler ndim : ", scalar.ndim)
print("Scaler item() : ", scalar.item())
print("Scaler item : ", scalar.item)

Scaler :  tensor(7)
Scaler dtype :  torch.int64
Scaler shape :  torch.Size([])
Scaler ndim :  0
Scaler item() :  7
Scaler item :  <built-in method item of Tensor object at 0x7f0f02188910>


In [27]:
# Vector
vector = torch.tensor([7, 7])
print("Vector : ", vector)
print("Vector dtype : ", vector.dtype)
print("Vector shape : ", vector.shape)
print("Vector ndim : ", vector.ndim)
#print(vector.item())
print("Vector item : ", vector.item)

Vector :  tensor([7, 7])
Vector dtype :  torch.int64
Vector shape :  torch.Size([2])
Vector ndim :  1
Vector item :  <built-in method item of Tensor object at 0x7f0f0218afd0>


In [29]:
# Matrix
Matrix = torch.tensor([[11, 22],
                       [33, 44]])

print("Maxtrix : ", Matrix)
print("Maxtrix dtype : ", Matrix.dtype)
print("Maxtrix shape : ", Matrix.shape)
print("Maxtrix ndim : ", Matrix.ndim)
#print(vector.item())
print("Maxtrix item : ", Matrix.item)

Maxtrix :  tensor([[11, 22],
        [33, 44]])
Maxtrix dtype :  torch.int64
Maxtrix shape :  torch.Size([2, 2])
Maxtrix ndim :  2
Maxtrix item :  <built-in method item of Tensor object at 0x7f0f0218be80>


In [52]:
# Tensor
Tensor = torch.tensor([[[11]],[[11]],[[11]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11]],

        [[11]],

        [[11]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([3, 1, 1])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f015580f0>


In [53]:
# Tensor
Tensor = torch.tensor([[[11, 22, 33]],[[11, 44, 55]],[[11, 66, 77]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22, 33]],

        [[11, 44, 55]],

        [[11, 66, 77]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([3, 1, 3])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f00ae8aa0>


In [46]:
# Tensor
Tensor = torch.tensor([[[11],
                        [44]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11],
         [44]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 2, 1])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f049c33e0>


In [44]:
# Tensor
Tensor = torch.tensor([[[11, 22],
                        [44, 55]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22],
         [44, 55]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 2, 2])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f021ef9d0>


In [45]:
# Tensor
Tensor = torch.tensor([[[11, 22, 33],
                        [44, 55, 66]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22, 33],
         [44, 55, 66]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 2, 3])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f01664870>


In [43]:
# Tensor
Tensor = torch.tensor([[[11, 22],
                        [44, 55],
                        [77, 88]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22],
         [44, 55],
         [77, 88]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 3, 2])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f01665a40>


In [39]:
# Tensor
Tensor = torch.tensor([[[11, 22, 33],
                        [44, 55, 66],
                        [77, 88, 99]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 3, 3])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f0151a5d0>


In [40]:
# Tensor
Tensor = torch.tensor([[[11, 22, 33, 33],
                        [44, 55, 66, 66],
                        [77, 88, 99, 99]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22, 33, 33],
         [44, 55, 66, 66],
         [77, 88, 99, 99]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 3, 4])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f0107a490>


In [41]:
# Tensor
Tensor = torch.tensor([[[11, 22, 33],
                        [44, 55, 66],
                        [77, 88, 99]],
                       [[11, 22, 33],
                        [44, 55, 66],
                        [77, 88, 99]],
                       [[11, 22, 33],
                        [44, 55, 66],
                        [77, 88, 99]]
                      ])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]],

        [[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]],

        [[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([3, 3, 3])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f0f01519d60>


In [57]:
# Creating a random tensor of size (3, 5)

random_tensor = torch.rand(size=(3,5))
random_tensor, random_tensor.dtype

(tensor([[0.2466, 0.1682, 0.5398, 0.6219, 0.1169],
         [0.2634, 0.2542, 0.3266, 0.7572, 0.6155],
         [0.8388, 0.8437, 0.4867, 0.2450, 0.7942]]),
 torch.float32)

In [58]:
# Creating a random tensor of size (1, 3, 5)

random_tensor = torch.rand(size=(1,3,5))
random_tensor, random_tensor.dtype

(tensor([[[0.0716, 0.1062, 0.7012, 0.9779, 0.2481],
          [0.3246, 0.5691, 0.6871, 0.9642, 0.3162],
          [0.8967, 0.9648, 0.1587, 0.7738, 0.2198]]]),
 torch.float32)

In [60]:
# Creating a random tensor of size (2, 3, 5)

random_tensor = torch.rand(size=(0,3,5))
random_tensor, random_tensor.dtype

(tensor([], size=(0, 3, 5)), torch.float32)

In [63]:
# Creating a random tensor of size (2, 3, 5)

random_tensor = torch.rand(size=(1,3,1))
random_tensor, random_tensor.dtype

(tensor([[[0.9527],
          [0.6970],
          [0.6318]]]),
 torch.float32)

In [64]:
# Creating a random tensor of size (100, 256, 256)

random_tensor = torch.rand(size=(100, 256, 256))
random_tensor, random_tensor.dtype

(tensor([[[9.3739e-01, 4.7087e-01, 6.2941e-01,  ..., 6.9142e-01,
           7.3608e-01, 8.3766e-01],
          [9.2969e-01, 7.8400e-01, 6.3650e-02,  ..., 5.1620e-01,
           2.6626e-01, 1.5958e-01],
          [9.2243e-01, 5.3744e-01, 8.9948e-01,  ..., 1.8958e-01,
           3.3332e-01, 3.2431e-01],
          ...,
          [3.0492e-01, 1.0410e-01, 9.6802e-01,  ..., 9.5465e-01,
           9.1415e-01, 3.0008e-01],
          [3.5766e-01, 4.7622e-01, 3.2830e-01,  ..., 5.7974e-01,
           2.6494e-01, 6.4820e-01],
          [3.1280e-01, 2.1775e-01, 7.6625e-01,  ..., 9.1959e-01,
           4.6312e-01, 3.2051e-01]],
 
         [[8.4878e-01, 1.7392e-01, 1.4532e-01,  ..., 3.0513e-01,
           6.6060e-01, 5.0563e-02],
          [3.9617e-01, 1.2970e-01, 3.8969e-01,  ..., 3.6767e-01,
           4.8858e-01, 1.1852e-01],
          [2.5952e-01, 4.0191e-01, 3.5912e-01,  ..., 6.4942e-01,
           3.7717e-01, 1.8155e-01],
          ...,
          [1.8920e-01, 2.2832e-01, 3.6588e-01,  ..., 4.258