In [1]:
import torch
import torch.cuda
print(torch.__version__)
print(torch.cuda)

2.6.0
<module 'torch.cuda' from '/opt/conda/lib/python3.12/site-packages/torch/cuda/__init__.py'>


In [2]:
# Scalar
scalar = torch.tensor(7)
print("Scaler : ", scalar)
print("Scaler dtype : ", scalar.dtype)
print("Scaler shape : ", scalar.shape)
print("Scaler ndim : ", scalar.ndim)
print("Scaler item() : ", scalar.item())
print("Scaler item : ", scalar.item)

Scaler :  tensor(7)
Scaler dtype :  torch.int64
Scaler shape :  torch.Size([])
Scaler ndim :  0
Scaler item() :  7
Scaler item :  <built-in method item of Tensor object at 0x7f09040ddd60>


In [3]:
# Vector
vector = torch.tensor([7, 7])
print("Vector : ", vector)
print("Vector dtype : ", vector.dtype)
print("Vector shape : ", vector.shape)
print("Vector ndim : ", vector.ndim)
#print(vector.item())
print("Vector item : ", vector.item)

Vector :  tensor([7, 7])
Vector dtype :  torch.int64
Vector shape :  torch.Size([2])
Vector ndim :  1
Vector item :  <built-in method item of Tensor object at 0x7f07ef7a2d50>


In [4]:
# Matrix
Matrix = torch.tensor([[11, 22],
                       [33, 44]])

print("Maxtrix : ", Matrix)
print("Maxtrix dtype : ", Matrix.dtype)
print("Maxtrix shape : ", Matrix.shape)
print("Maxtrix ndim : ", Matrix.ndim)
#print(vector.item())
print("Maxtrix item : ", Matrix.item)

Maxtrix :  tensor([[11, 22],
        [33, 44]])
Maxtrix dtype :  torch.int64
Maxtrix shape :  torch.Size([2, 2])
Maxtrix ndim :  2
Maxtrix item :  <built-in method item of Tensor object at 0x7f07ef7a0b90>


In [5]:
# Tensor
Tensor = torch.tensor([[[11]],[[11]],[[11]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11]],

        [[11]],

        [[11]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([3, 1, 1])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f07ef7a3930>


In [6]:
# Tensor
Tensor = torch.tensor([[[11, 22, 33]],[[11, 44, 55]],[[11, 66, 77]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22, 33]],

        [[11, 44, 55]],

        [[11, 66, 77]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([3, 1, 3])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f07ef7c5f40>


In [7]:
# Tensor
Tensor = torch.tensor([[[11],
                        [44]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11],
         [44]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 2, 1])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f07ef7c6a80>


In [8]:
# Tensor
Tensor = torch.tensor([[[11, 22],
                        [44, 55]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22],
         [44, 55]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 2, 2])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f07ef7c7610>


In [9]:
# Tensor
Tensor = torch.tensor([[[11, 22, 33],
                        [44, 55, 66]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22, 33],
         [44, 55, 66]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 2, 3])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f07ef7c7250>


In [10]:
# Tensor
Tensor = torch.tensor([[[11, 22],
                        [44, 55],
                        [77, 88]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22],
         [44, 55],
         [77, 88]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 3, 2])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f07ef7c43c0>


In [11]:
# Tensor
Tensor = torch.tensor([[[11, 22, 33],
                        [44, 55, 66],
                        [77, 88, 99]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 3, 3])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f07ef7c5c20>


In [12]:
# Tensor
Tensor = torch.tensor([[[11, 22, 33, 33],
                        [44, 55, 66, 66],
                        [77, 88, 99, 99]]])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22, 33, 33],
         [44, 55, 66, 66],
         [77, 88, 99, 99]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([1, 3, 4])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f07ef5ee940>


In [13]:
# Tensor
Tensor = torch.tensor([[[11, 22, 33],
                        [44, 55, 66],
                        [77, 88, 99]],
                       [[11, 22, 33],
                        [44, 55, 66],
                        [77, 88, 99]],
                       [[11, 22, 33],
                        [44, 55, 66],
                        [77, 88, 99]]
                      ])
print("Tensor : ", Tensor)
print("Tensor dtype : ", Tensor.dtype)
print("Tensor shape : ", Tensor.shape)
print("Tensor ndim : ", Tensor.ndim)
#print(vector.item())
print("Tensor item : ", Tensor.item)

Tensor :  tensor([[[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]],

        [[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]],

        [[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]]])
Tensor dtype :  torch.int64
Tensor shape :  torch.Size([3, 3, 3])
Tensor ndim :  3
Tensor item :  <built-in method item of Tensor object at 0x7f07ef5ef250>


In [14]:
# Creating a random tensor of size (3, 5)

random_tensor = torch.rand(size=(3,5))
random_tensor, random_tensor.dtype

(tensor([[0.3181, 0.8759, 0.9403, 0.1948, 0.7516],
         [0.1881, 0.0076, 0.0679, 0.7246, 0.5465],
         [0.2737, 0.6134, 0.9367, 0.9149, 0.4022]]),
 torch.float32)

In [15]:
# Creating a random tensor of size (1, 3, 5)

random_tensor = torch.rand(size=(1,3,5))
random_tensor, random_tensor.dtype

(tensor([[[0.5895, 0.1631, 0.4202, 0.6573, 0.2104],
          [0.5132, 0.4421, 0.6293, 0.1132, 0.4257],
          [0.3463, 0.8861, 0.0225, 0.6487, 0.1878]]]),
 torch.float32)

In [16]:
# Creating a random tensor of size (2, 3, 5)

random_tensor = torch.rand(size=(0,3,5))
random_tensor, random_tensor.dtype

(tensor([], size=(0, 3, 5)), torch.float32)

In [17]:
# Creating a random tensor of size (2, 3, 5)

random_tensor = torch.rand(size=(1,3,1))
random_tensor, random_tensor.dtype

(tensor([[[0.1860],
          [0.1738],
          [0.6727]]]),
 torch.float32)

In [18]:
# Creating a random tensor of size (100, 256, 256)

random_tensor = torch.rand(size=(100, 256, 256))
random_tensor, random_tensor.dtype, random_tensor.ndim, random_tensor.shape

(tensor([[[7.7812e-01, 9.7400e-01, 7.5853e-01,  ..., 9.0969e-01,
           6.0185e-01, 4.5624e-01],
          [6.1165e-01, 8.8120e-01, 1.3001e-01,  ..., 4.7076e-01,
           1.2821e-01, 3.8448e-01],
          [4.3574e-01, 9.9987e-01, 8.9947e-01,  ..., 4.1811e-01,
           3.8160e-01, 2.8138e-01],
          ...,
          [5.6566e-02, 6.9314e-01, 7.1415e-01,  ..., 2.5258e-01,
           1.5227e-01, 9.4204e-01],
          [1.5321e-01, 7.7936e-01, 2.7708e-01,  ..., 7.1133e-01,
           2.3778e-01, 8.6535e-01],
          [1.0125e-01, 4.9089e-01, 6.2998e-01,  ..., 1.1021e-01,
           8.7731e-01, 9.8604e-01]],
 
         [[8.6153e-01, 1.9814e-01, 2.7544e-01,  ..., 8.4526e-01,
           6.7830e-01, 8.1691e-01],
          [5.2860e-01, 4.9170e-01, 6.5291e-01,  ..., 5.8256e-01,
           1.8943e-01, 7.3491e-01],
          [5.5259e-01, 5.8473e-01, 4.1489e-01,  ..., 5.8518e-01,
           1.6871e-02, 1.7850e-01],
          ...,
          [8.5823e-01, 4.8939e-01, 1.6627e-01,  ..., 3.477

In [19]:
# Zero Tensors of random size

zero = torch.zeros(size=(2, 3, 4))

zero, zero.dtype, zero.shape, zero.ndim

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 torch.float32,
 torch.Size([2, 3, 4]),
 3)

In [20]:
# One Tensors of random size

Ones = torch.ones(size=(1, 2, 3))

Ones, Ones.dtype, Ones.shape, Ones.ndim

(tensor([[[1., 1., 1.],
          [1., 1., 1.]]]),
 torch.float32,
 torch.Size([1, 2, 3]),
 3)

In [21]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                      dtype = None, 
                      device = None, 
                      requires_grad = False
                     )

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [22]:
# Of datatype float16 - 2 bytes
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [23]:
# Of datatype float16 - 2 bytes
int_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.int16)
int_16_tensor, int_16_tensor.dtype

(tensor([3, 6, 9], dtype=torch.int16), torch.int16)

### Getting information from tensors¶

In [24]:
# Create a tensor
some_tensor = torch.rand(3, 5)

print(some_tensor)
print(f"Shape of Tensor : ", {some_tensor.shape})
print(f"DataType of Tensor : {some_tensor.dtype}")
print(f"Device Tensor is stored on : {some_tensor.device}")


tensor([[0.1850, 0.8125, 0.5145, 0.3511, 0.5707],
        [0.0502, 0.4220, 0.2546, 0.9469, 0.2110],
        [0.9404, 0.2604, 0.0444, 0.1985, 0.9243]])
Shape of Tensor :  {torch.Size([3, 5])}
DataType of Tensor : torch.float32
Device Tensor is stored on : cpu


## Manipulating tensors (tensor operations)

### Basic operations

In [25]:
# Creating a tensor and adding the scalar value to it
tensor = torch.tensor([11, 22, 33])
print( tensor - 3) # tensor does not change value until you assign the video


tensor = tensor + 123
print(tensor.shape)
print(tensor)

tensor = tensor * 10
print(tensor)

tensor([ 8, 19, 30])
torch.Size([3])
tensor([134, 145, 156])
tensor([1340, 1450, 1560])


In [26]:
tensor_2d = torch.tensor([[11, 22, 33]])
tensor_2d = tensor_2d + 123
print(tensor_2d.shape)
print(tensor_2d)

tensor_2d = tensor_2d * 100
print(tensor_2d)

torch.Size([1, 3])
tensor([[134, 145, 156]])
tensor([[13400, 14500, 15600]])


In [27]:
tensor_3d = torch.tensor([[[11, 22, 33]]])
tensor_3d = tensor_3d + 123
print(tensor_3d.shape)
print(tensor_3d)

tensor_3d = tensor_3d * 1000
print(tensor_3d)

torch.Size([1, 1, 3])
tensor([[[134, 145, 156]]])
tensor([[[134000, 145000, 156000]]])


In [28]:
### You can also use torch functions to add or multiply

tensor = torch.randint(low = 0, high = 100, size = (1, 2, 3), dtype=torch.int8)

tensor

tensor([[[80, 30, 81],
         [ 2, 91, 73]]], dtype=torch.int8)

In [29]:
torch.multiply(tensor, 10)

tensor([[[  32,   44,   42],
         [  20, -114,  -38]]], dtype=torch.int8)

In [30]:
tensor = torch.randint(low = 0, high = 100, size = (1, 2, 3), dtype=torch.int8)
torch.multiply(tensor, 10.0)

tensor([[[870., 980., 800.],
         [930., 720., 440.]]])

In [31]:
tensor = torch.rand((2, 3), dtype = torch.float32)
print(tensor, "*", tensor)
print("\nEquals:", tensor * tensor)

tensor([[0.4503, 0.1184, 0.6262],
        [0.4302, 0.8035, 0.9793]]) * tensor([[0.4503, 0.1184, 0.6262],
        [0.4302, 0.8035, 0.9793]])

Equals: tensor([[0.2028, 0.0140, 0.3921],
        [0.1851, 0.6455, 0.9591]])


In [32]:
tensor1 = torch.rand((2, 3), dtype = torch.float32)

tensor2 = torch.rand((2, 3), dtype = torch.float32)

print(tensor1, "*", tensor1)
print("\nEquals:", tensor * tensor)

tensor([[0.6177, 0.6229, 0.5148],
        [0.3171, 0.3543, 0.2656]]) * tensor([[0.6177, 0.6229, 0.5148],
        [0.3171, 0.3543, 0.2656]])

Equals: tensor([[0.2028, 0.0140, 0.3921],
        [0.1851, 0.6455, 0.9591]])


In [33]:
# Element-wise multiplication (“multiply matching cells”)
tensor1 = torch.rand((2, 3), dtype = torch.float32)
print(tensor1.shape, tensor1.ndim)

tensor2 = torch.rand((2, 3), dtype = torch.float32)
print(tensor2.shape, tensor2.ndim)

print("\n", tensor1, "\n*\n", tensor2)
print("\nEquals:", tensor1 * tensor2)

torch.Size([2, 3]) 2
torch.Size([2, 3]) 2

 tensor([[0.7278, 0.2359, 0.8025],
        [0.7010, 0.4122, 0.9861]]) 
*
 tensor([[0.2785, 0.8244, 0.3759],
        [0.9324, 0.5860, 0.7622]])

Equals: tensor([[0.2027, 0.1945, 0.3017],
        [0.6536, 0.2415, 0.7516]])


In [34]:
# Element-wise multiplication (“multiply matching cells”)
tensor1 = torch.rand((2, 3), dtype = torch.float32)
print(tensor1.shape, tensor1.ndim)

tensor2 = torch.rand((3, 2), dtype = torch.float32)
print(tensor2.shape, tensor2.ndim)

print("\n", tensor1, "\n*\n", tensor2)
print("\nEquals:", tensor1 * tensor2)

torch.Size([2, 3]) 2
torch.Size([3, 2]) 2

 tensor([[0.4109, 0.6404, 0.0856],
        [0.4385, 0.4279, 0.8125]]) 
*
 tensor([[0.7700, 0.5251],
        [0.3662, 0.8156],
        [0.8107, 0.4083]])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [ ]:
# tensor1 @ tensor2 — Matrix multiplication

tensor1 = torch.rand((2, 3), dtype = torch.float32)
print(tensor1.shape, tensor1.ndim)

tensor2 = torch.rand((3, 2), dtype = torch.float32)
print(tensor2.shape, tensor2.ndim)

print("\n", tensor1, "\n*\n", tensor2)
print("\nEquals:", tensor1 @ tensor2)

In [35]:
# This is dot product of two tensors

tensor1 = torch.rand((2, 3), dtype = torch.float32)
print(tensor1.shape, tensor1.ndim)

tensor2 = torch.rand((3, 2), dtype = torch.float32)
print(tensor2.shape, tensor2.ndim)

print("\n", tensor1, "\n*\n", tensor2)
print("\nEquals:", tensor1 @ tensor2)

torch.Size([2, 3]) 2
torch.Size([3, 2]) 2

 tensor([[0.4996, 0.0753, 0.5912],
        [0.6784, 0.8189, 0.1556]]) 
*
 tensor([[0.5925, 0.8226],
        [0.9059, 0.9318],
        [0.2347, 0.9621]])

Equals: tensor([[0.5030, 1.0500],
        [1.1804, 1.4709]])


In [36]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [37]:
# Element wise matrix multiplication

print(tensor * tensor)

tensor([1, 4, 9])


In [38]:
# Matrix Multiplication
print(torch.matmul(tensor, tensor))

tensor(14)


In [39]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))

True
1
NVIDIA A10G


In [40]:
!nvidia-smi

Sun Jan 11 05:12:34 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.105.08             Driver Version: 580.105.08     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A10G                    On  |   00000000:00:1E.0 Off |                    0 |
|  0%   28C    P8             18W /  300W |       3MiB /  23028MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [41]:
# Matrix Multiplication
print(torch.matmul(tensor, tensor))

tensor(14)


In [42]:
tensor = torch.rand(2, 3).to(device)
result = tensor * tensor
print(tensor.device)
print(result.device)

NameError: name 'device' is not defined

In [ ]:
%%time
value = 0

for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

In [ ]:
%%time
torch.matmul(tensor, tensor)

### One of the most common errors in deep learning (shape errors)

In [ ]:
# Shape need to be in the right way

tensor_A = torch.tensor([[1, 2], 
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
print(tensor_A)
tensor_B = torch.tensor( [[7, 8],
                          [10, 11],
                          [12, 13]], dtype = torch.float32)
print(tensor_B)

torch.matmul(tensor_A, tensor_B)

In [ ]:
# Shape need to be in the right way

tensor_A = torch.tensor([[1, 2], 
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
print(tensor_A)
tensor_B = torch.tensor( [[7, 8],
                          [10, 11],
                          [12, 13]], dtype = torch.float32)
print(tensor_B.T)

torch.matmul(tensor_A, tensor_B)

In [43]:
# Now the inner dimension of matrix multiplication should match, after transpose it should match
print(f"Orginal Shape of Tensor A: = {tensor_A.shape}, Tensor b : = {tensor_B.shape}\n")
print(f"New Shapes: Tensor A : = { tensor_A.shape} ( same as above ), Tensor B : = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <-- Inner Dimensions are same\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape : {output.shape}")

NameError: name 'tensor_A' is not defined

In [44]:
# torch.mm is a shortcut that I can use
torch.mm(tensor_A, tensor_B.T)

NameError: name 'tensor_A' is not defined

In [45]:
torch.manual_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
linear = torch.nn.Linear(in_features = 2, out_features = 32, bias = True, device = device)

x = tensor_A.to(device)
output = linear(x)

print(f"Input shape : {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

NameError: name 'tensor_A' is not defined

### Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
# Create a tensor
x = torch.arange(33, 100, 3.3)

x

In [46]:
print(f"Minimum : {x.min()}")
print(f"Maximum : {x.max()}")
print(f"Mean : {x.type(torch.float32).mean()}")
print(f"Sum : {x.sum()}")

NameError: name 'x' is not defined

In [47]:
float32_tensor = torch.rand(23)
print(tensor)
print(f"Index where Maximum value occurs : {tensor.argmax()}")
print(f"Index where Maximum value occurs : {tensor.argmin()}")

tensor([1, 2, 3])
Index where Maximum value occurs : 2
Index where Maximum value occurs : 0


In [48]:
tensor.dtype

torch.int64

In [49]:
float16_tensor = torch.rand(23, dtype = torch.float16)
print(tensor_2)

NameError: name 'tensor_2' is not defined

In [50]:
import random

int8_tensor = torch.rand(23, dtype = torch.float32)*100

int8_tensor = int8_tensor.to(dtype = torch.int8)

print(int8_tensor)

tensor([78, 58, 75, 19,  0, 30, 11, 91, 64, 70, 65, 49, 89, 14, 53, 15, 65, 32,
        65, 39, 91, 20, 20], dtype=torch.int8)


In [51]:
int8_tensor.stride()

(1,)

In [52]:
tensor = torch.rand(2,3)
tensor

tensor([[0.2018, 0.9497, 0.6666],
        [0.9811, 0.0874, 0.0041]])

In [53]:
tensor.stride()

(3, 1)

In [54]:
tensor = torch.rand(2,3,3)
tensor

tensor([[[0.1088, 0.1637, 0.7025],
         [0.6790, 0.9155, 0.2418],
         [0.1591, 0.7653, 0.2979]],

        [[0.8035, 0.3813, 0.7860],
         [0.1115, 0.2477, 0.6524],
         [0.6057, 0.3725, 0.7980]]])

In [55]:
tensor.stride()

(9, 3, 1)

In [56]:
data = [[0, 1], [2, 3]]
tensor = tensor.new_tensor(data)
tensor

tensor([[0., 1.],
        [2., 3.]])

In [57]:
tensor = torch.rand(2,3,3)
tensor

tensor([[[0.8399, 0.1374, 0.2331],
         [0.9578, 0.3313, 0.3227],
         [0.0162, 0.2137, 0.6249]],

        [[0.4340, 0.1371, 0.5117],
         [0.1585, 0.0758, 0.2247],
         [0.0624, 0.1816, 0.9998]]])

In [58]:
tensor.shape

torch.Size([2, 3, 3])

In [59]:
x = torch.arange(1., 10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [60]:
# Adding an extra dimension
x_reshaped = x.reshape(3, -1)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [61]:
# Adding an extra dimension
x_reshaped = x.reshape(-1, 3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [62]:
x = torch.arange(1., 10.)
x_reshaped = x.reshape(-1, 9)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [63]:
# Adding an extra dimension
z = x_reshaped
z[:, 0] = 5
x_reshaped, z
# changing value in z x_reshaped changed z

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [64]:
# View()
z = x.view(-1, 9)
z, z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
z[:, 0] = 123
z, x

(tensor([[123.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]]),
 tensor([123.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]))

In [66]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[123.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [123.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [123.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [123.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]])

In [67]:
print(f"Previous tensor: {x_stacked}")
print(f"Previous shape: {x_stacked.shape}")

#Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[123.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [123.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [123.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [123.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]])
Previous shape: torch.Size([4, 9])

New tensor: tensor([123.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.])
New shape: torch.Size([9])


In [68]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([123.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.])
Previous shape: torch.Size([9])

New tensor: tensor([[123.],
        [  2.],
        [  3.],
        [  4.],
        [  5.],
        [  6.],
        [  7.],
        [  8.],
        [  9.]])
New shape: torch.Size([9, 1])


In [73]:
# Permute 
x_original = torch.rand(1, 2, 3)

x_permuted = x_original.permute(1, 2, 0)

print(x_original)
print(x_permuted)

tensor([[[0.9596, 0.8748, 0.5055],
         [0.7411, 0.3252, 0.0639]]])
tensor([[[0.9596],
         [0.8748],
         [0.5055]],

        [[0.7411],
         [0.3252],
         [0.0639]]])


# Indexing (selecting data from tensors)

### Create a tensor

In [74]:
import torch
x = torch.arange(1,10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [76]:
# Let's index bracket by bracket
print(f"First Square Bracket:\n{x[0]}")
print(f"First Square Bracket:\n{x[0][0]}")
print(f"First Square Bracket:\n{x[0][0][0]}")

First Square Bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
First Square Bracket:
tensor([1, 2, 3])
First Square Bracket:
1


In [77]:
x[:,0]

tensor([[1, 2, 3]])

In [79]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [86]:
x[:, :2, :2]

tensor([[[1, 2],
         [4, 5]]])

### Running on GPU

In [87]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [88]:
torch.cuda.device_count()

1

In [89]:
torch = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([[[0.8399, 0.1374, 0.2331],
         [0.9578, 0.3313, 0.3227],
         [0.0162, 0.2137, 0.6249]],

        [[0.4340, 0.1371, 0.5117],
         [0.1585, 0.0758, 0.2247],
         [0.0624, 0.1816, 0.9998]]]) cpu


In [90]:
tensor_on_gpu = torch.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [92]:
torch.cuda.memory.list_gpu_processes()


AttributeError: 'builtin_function_or_method' object has no attribute 'memory'

In [93]:
print(type(torch.cuda))


<class 'builtin_function_or_method'>
