# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch

# Create random tensor
X = torch.rand(7, 7)
X

tensor([[0.2199, 0.3574, 0.5753, 0.1386, 0.8750, 0.3974, 0.9199],
        [0.6411, 0.0123, 0.6711, 0.3340, 0.8543, 0.7579, 0.0471],
        [0.2704, 0.0106, 0.6977, 0.8387, 0.5114, 0.5992, 0.2399],
        [0.5936, 0.4743, 0.8071, 0.0724, 0.4159, 0.7734, 0.2258],
        [0.9901, 0.1668, 0.0215, 0.8729, 0.8829, 0.9310, 0.7357],
        [0.7979, 0.5102, 0.9994, 0.4689, 0.7021, 0.3642, 0.5183],
        [0.6530, 0.9770, 0.9866, 0.5722, 0.4291, 0.4367, 0.1976]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [12]:
# Create another random tensor
Y = torch.rand(1,7)
print(f"Y Matrix Multiplication\n{Y}\n")

# Perform matrix multiplication 
print(f"\nX shape {X.shape}, Y shape {Y.shape}")
Z = torch.matmul(X, Y.T)
print(f"\nZ is matrix \n{Z}")

Y Matrix Multiplication
tensor([[0.1642, 0.5414, 0.9985, 0.0504, 0.0793, 0.4105, 0.5470]])


X shape torch.Size([7, 7]), Y shape torch.Size([1, 7])

Z is matrix 
tensor([[1.5467],
        [1.2034],
        [1.2067],
        [1.6377],
        [1.1729],
        [1.9174],
        [1.9715]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [17]:
# Set manual seed
torch.manual_seed(10)

# Create two random tensors
X = torch.rand(2, 3)
Y = torch.rand(5, 3)
print(f" X matrix is \n{X}, and Y matrix \n{Y}")

# Matrix multiply tensors
Z = torch.mm(X, Y.T)
print(f" Final Matrix Multiplication \n{Z}")

 X matrix is 
tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]]), and Y matrix 
tensor([[0.6938, 0.9693, 0.6178],
        [0.3304, 0.5479, 0.4440],
        [0.7041, 0.5573, 0.6959],
        [0.9849, 0.2924, 0.4823],
        [0.6150, 0.4967, 0.4521]])
 Final Matrix Multiplication 
tensor([[0.9789, 0.5547, 0.8091, 0.7431, 0.6629],
        [0.8885, 0.5032, 0.8388, 0.8669, 0.6707]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [18]:
# Set random seed on the GPU
torch.cuda.manual_seed(10)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [42]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.current_device())
print(torch.cuda.device_count())
print(torch.cuda.get_device_capability('cuda:0'))
print(torch.cuda.get_device_name())
print(torch.cuda.get_device_properties())
print(torch.cuda.list_gpu_processes())
print(torch.cuda.is_available())
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device : {device}")
# Create two random tensors on GPU
X = torch.rand(2, 5).to(device)
Y = torch.rand(3, 5).to(device)

print(f"\n\nX Matrix : \n{X}\nY Matrix : \n{Y}")

0
1
(8, 6)
NVIDIA A10G
_CudaDeviceProperties(name='NVIDIA A10G', major=8, minor=6, total_memory=22587MB, multi_processor_count=80, uuid=f16d33e3-06c1-0fec-929f-374f80299cd5, L2_cache_size=6MB)
pynvml module not found, please install pynvml
True
Device : cuda


X Matrix : 
tensor([[0.6184, 0.0132, 0.2650, 0.7495, 0.1535],
        [0.3224, 0.7908, 0.7567, 0.1129, 0.7221]], device='cuda:0')
Y Matrix : 
tensor([[0.1385, 0.9382, 0.4488, 0.5681, 0.6448],
        [0.1155, 0.8566, 0.1693, 0.0540, 0.5942],
        [0.6414, 0.8605, 0.0916, 0.3973, 0.8914]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [44]:
# Perform matmul on tensor_A and tensor_B
tensor_A = X
tensor_B = Y.T

Z = torch.mm(tensor_A, tensor_B)
print(f"Final Tensor Z : \n{Z}")

Final Tensor Z : 
tensor([[0.7417, 0.2592, 0.8668],
        [1.6559, 1.2779, 1.6450]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [47]:
# Find max
max_value = Z.max()

# Find min
min_val = Z.min()

print(f" Maximum Value : {max_value}\n Minimum Value : {min_val}")

 Maximum Value : 1.655875563621521
 Minimum Value : 0.25922849774360657


### 9. Find the maximum and minimum index values of the output of 7.

In [48]:
# Find max
max_value = torch.argmax(Z)

# Find min
min_val = torch.argmin(Z)

print(f" Maximum Value : {max_value}\n Minimum Value : {min_val}")

 Maximum Value : 3
 Minimum Value : 1



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [53]:
# Set seed
torch.manual_seed(7)

# Create random tensor
Tensor_X = torch.rand(1, 1, 1, 10)

# Remove single dimensions
Tensor_X_squeezed = Tensor_X.squeeze()
Tensor_X_squeezed.shape
print(f"\nTensor_X_squeezed \n{Tensor_X_squeezed}")


# Print out tensors and their shapes
print(f"Tensor X Shape : {Tensor_X.shape},\nTensor X \n{Tensor_X}")

print(f"\nTensor_X_squeezed : {Tensor_X_squeezed.shape},\nTensor_X_squeezed \n{Tensor_X_squeezed}")



Tensor_X_squeezed 
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Tensor X Shape : torch.Size([1, 1, 1, 10]),
Tensor X 
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

Tensor_X_squeezed : torch.Size([10]),
Tensor_X_squeezed 
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])


In [1]:
import torch
print(torch.cuda)
torch.cuda.memory.list_gpu_processes()

<module 'torch.cuda' from '/opt/conda/lib/python3.12/site-packages/torch/cuda/__init__.py'>


'pynvml module not found, please install pynvml'